version: '3'
services:
  mongo:
    hostname: mongo
    image: mongo:latest
    logging:
      driver: none

  postdog:
    build:
      context: ..
      dockerfile: deployments/storetest.Dockerfile
    environment:
      - TZ=UTC
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
