// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go

// Package mock_queue is a generated GoMock package.
package mock_queue

import (
	context "context"
	postdog "github.com/bounoable/postdog"
	send "github.com/bounoable/postdog/send"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMailer is a mock of Mailer interface
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
}

// MockMailerMockRecorder is the mock recorder for MockMailer
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendConfig mocks base method
func (m *MockMailer) SendConfig(arg0 context.Context, arg1 postdog.Mail, arg2 send.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfig", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfig indicates an expected call of SendConfig
func (mr *MockMailerMockRecorder) SendConfig(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfig", reflect.TypeOf((*MockMailer)(nil).SendConfig), arg0, arg1, arg2)
}
