// Code generated by MockGen. DO NOT EDIT.
// Source: postdog.go

// Package mock_postdog is a generated GoMock package.
package mock_postdog

import (
	context "context"
	postdog "github.com/bounoable/postdog"
	gomock "github.com/golang/mock/gomock"
	mail "net/mail"
	reflect "reflect"
)

// MockTransport is a mock of Transport interface
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
}

// MockTransportMockRecorder is the mock recorder for MockTransport
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockTransport) Send(arg0 context.Context, arg1 postdog.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockTransportMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTransport)(nil).Send), arg0, arg1)
}

// MockMiddleware is a mock of Middleware interface
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// Handle mocks base method
func (m *MockMiddleware) Handle(arg0 context.Context, arg1 postdog.Mail, arg2 func(context.Context, postdog.Mail) (postdog.Mail, error)) (postdog.Mail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0, arg1, arg2)
	ret0, _ := ret[0].(postdog.Mail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle
func (mr *MockMiddlewareMockRecorder) Handle(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockMiddleware)(nil).Handle), arg0, arg1, arg2)
}

// MockMail is a mock of Mail interface
type MockMail struct {
	ctrl     *gomock.Controller
	recorder *MockMailMockRecorder
}

// MockMailMockRecorder is the mock recorder for MockMail
type MockMailMockRecorder struct {
	mock *MockMail
}

// NewMockMail creates a new mock instance
func NewMockMail(ctrl *gomock.Controller) *MockMail {
	mock := &MockMail{ctrl: ctrl}
	mock.recorder = &MockMailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMail) EXPECT() *MockMailMockRecorder {
	return m.recorder
}

// From mocks base method
func (m *MockMail) From() mail.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "From")
	ret0, _ := ret[0].(mail.Address)
	return ret0
}

// From indicates an expected call of From
func (mr *MockMailMockRecorder) From() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "From", reflect.TypeOf((*MockMail)(nil).From))
}

// Recipients mocks base method
func (m *MockMail) Recipients() []mail.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recipients")
	ret0, _ := ret[0].([]mail.Address)
	return ret0
}

// Recipients indicates an expected call of Recipients
func (mr *MockMailMockRecorder) Recipients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recipients", reflect.TypeOf((*MockMail)(nil).Recipients))
}

// RFC mocks base method
func (m *MockMail) RFC() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RFC")
	ret0, _ := ret[0].(string)
	return ret0
}

// RFC indicates an expected call of RFC
func (mr *MockMailMockRecorder) RFC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RFC", reflect.TypeOf((*MockMail)(nil).RFC))
}
